### ISSUE TITLE
[BUG]Null pointer on a mouse hop.

### ISSUE THREAD

**Issue by JohnRThomas** [JohnRThomas/Exia-Mining-All-In-One#24]
Try to recreate:
java.lang.NullPointerException
 at nul.iIiiiIiiIiiI.do(Unknown Source)
 at com.runemate.game.api.hybrid.input.Mouse$PathGenerator.hop(Unknown Source)
 at rm.cOm4.const(gb:431)
 at rm.cOm4.true(gb:156)
 at scripts.ExiaMinerAIO.onLoop(rb:36)
 at com.runemate.game.api.script.framework.LoopingScript.run(Unknown Source)
 at com.runemate.game.api.script.framework.AbstractScript.start(Unknown Source)
 at nul.iiIIIIiIIIiI.run(Unknown Source)
1.3.6.2 - OSRS

**Comment by Kneckter** [comment]
Might be hard to recreate this. nul.iIiiiIiiIiiI.do is from the client.

**Comment by JohnRThomas** [comment]
Yeah, I added the ErrorHandler class as a bandaid for all of these null pointers and I'm working with cloud to get the stack traces fixed.
